name: my_taxi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^10.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/NotoKufiArabic-VariableFont_wght.ttf
        - asset: assets/fonts/NotoKufiArabic-VariableFont_wght.ttf
          weight: 700

    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/FacultyGlyphic-Regular.ttf
        
          style: italic